version: "3.7"
services:
  db:
      image: postgres:11.5      
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=ecomerce_omni
      expose:
        - 5432
      ports:
        - '5432:5432'
      volumes:
        - ./data/db:/var/lib/postgresql/data
  app:
    build:
      context: .
    expose:
        - 8000
    ports:
      - "8000:8000"
    environment:
        - DB_USER=admin
        - DB_PASS=admin
        - DB_HOST=db
        - DB_PORT=5432
        - DB_NAME=ecomerce_omni
    volumes:
      - ../prueba_omni:/prueba_omni
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db